project_id = "zhdjvfylxgtiphldjtqf"

[functions.analyze-lab-report]
verify_jwt = true

[functions.analyze-lab-report-ai]
verify_jwt = true

[functions.create-lab-order]
verify_jwt = true

[functions.create-fullscript-account]
verify_jwt = true